/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/midleware/authStorage` | `/midleware/authStorage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notification/page` | `/notification/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/page` | `/settings/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showcase/page` | `/showcase/page`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/midleware/authStorage` | `/midleware/authStorage`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notification/page` | `/notification/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/page` | `/profile/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings/page` | `/settings/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/showcase/page` | `/showcase/page`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/midleware/authStorage${`?${string}` | `#${string}` | ''}` | `/midleware/authStorage${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/page${`?${string}` | `#${string}` | ''}` | `/signup/page${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/styles${`?${string}` | `#${string}` | ''}` | `/signup/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notification/page${`?${string}` | `#${string}` | ''}` | `/notification/page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/page${`?${string}` | `#${string}` | ''}` | `/profile/page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings/page${`?${string}` | `#${string}` | ''}` | `/settings/page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/showcase/page${`?${string}` | `#${string}` | ''}` | `/showcase/page${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/midleware/authStorage` | `/midleware/authStorage`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notification/page` | `/notification/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings/page` | `/settings/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showcase/page` | `/showcase/page`; params?: Router.UnknownInputParams; };
    }
  }
}
