/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notification/page` | `/notification/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notification/styles` | `/notification/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/styles` | `/profile/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showcase/page` | `/showcase/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showcase/styles` | `/showcase/styles`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatPhoneNumber`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notification/page` | `/notification/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/notification/styles` | `/notification/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/page` | `/profile/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/profile/styles` | `/profile/styles`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/showcase/page` | `/showcase/page`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/showcase/styles` | `/showcase/styles`; params?: Router.UnknownOutputParams; } | { pathname: `/utils/formatPhoneNumber`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/styles${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/page${`?${string}` | `#${string}` | ''}` | `/signup/page${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/signup/styles${`?${string}` | `#${string}` | ''}` | `/signup/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notification/page${`?${string}` | `#${string}` | ''}` | `/notification/page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/notification/styles${`?${string}` | `#${string}` | ''}` | `/notification/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/page${`?${string}` | `#${string}` | ''}` | `/profile/page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/profile/styles${`?${string}` | `#${string}` | ''}` | `/profile/styles${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/showcase/page${`?${string}` | `#${string}` | ''}` | `/showcase/page${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/showcase/styles${`?${string}` | `#${string}` | ''}` | `/showcase/styles${`?${string}` | `#${string}` | ''}` | `/utils/formatPhoneNumber${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/styles`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/page` | `/signup/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/signup/styles` | `/signup/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notification/page` | `/notification/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/notification/styles` | `/notification/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/page` | `/profile/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/profile/styles` | `/profile/styles`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showcase/page` | `/showcase/page`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/showcase/styles` | `/showcase/styles`; params?: Router.UnknownInputParams; } | { pathname: `/utils/formatPhoneNumber`; params?: Router.UnknownInputParams; };
    }
  }
}
